[keys.normal]
up = "no_op"
down = "no_op" 
left = "no_op"
right = "no_op"

[keys.select]
up = "no_op"
down = "no_op"
left = "no_op" 
right = "no_op"

[keys.insert]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
